[SPIRV_Headers]
git-tree-sha1 = "a5442a3c0abe85aa74a261e48e0941b91d553a65"

    [[SPIRV_Headers.download]]
    sha256 = "3b3cb6c5ab84c790dbe0f4f4efbee58a52c7639cfabfbb1d23e8d60c546db18d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Headers_jll.jl/releases/download/SPIRV_Headers-v1.5.4+0/SPIRV_Headers.v1.5.4.any.tar.gz"
